name: Build and Deploy App To Firebase App Distribution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'corretto'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and Deploy Debug
      run: ./gradlew assembleDebug appDistributionUploadDebug
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
